const foodProducts = [
  {
    id: 1,
    img: "https://picsum.photos/300?random=1",
    title: "Fresh Burger",
    code: "FD1001",
    category: "Burger",
    discountPercent: 10,
    price: 250,
    discountPrice: 225,
    stock: 40,
    offer: true,
  },
  {
    id: 2,
    img: "https://picsum.photos/300?random=2",
    title: "Chicken Pizza",
    code: "FD1002",
    category: "Pizza",
    discountPercent: 15,
    price: 650,
    discountPrice: 552,
    stock: 22,
    offer: true,
  },
  {
    id: 3,
    img: "https://picsum.photos/300?random=3",
    title: "French Fries",
    code: "FD1003",
    category: "Snacks",
    discountPercent: 8,
    price: 180,
    discountPrice: 165,
    stock: 55,
    offer: false,
  },
  {
    id: 4,
    img: "https://picsum.photos/300?random=4",
    title: "Cold Coffee",
    code: "FD1004",
    category: "Drinks",
    discountPercent: 5,
    price: 220,
    discountPrice: 209,
    stock: 60,
    offer: false,
  },
  {
    id: 5,
    img: "https://picsum.photos/300?random=5",
    title: "Chocolate Cake",
    code: "FD1005",
    category: "Dessert",
    discountPercent: 20,
    price: 500,
    discountPrice: 400,
    stock: 15,
    offer: true,
  },
  {
    id: 6,
    img: "https://picsum.photos/300?random=6",
    title: "Beef Shawarma",
    code: "FD1006",
    category: "Fast Food",
    discountPercent: 12,
    price: 320,
    discountPrice: 281,
    stock: 33,
    offer: true,
  },
  {
    id: 7,
    img: "https://picsum.photos/300?random=7",
    title: "Chicken Sandwich",
    code: "FD1007",
    category: "Snacks",
    discountPercent: 10,
    price: 280,
    discountPrice: 252,
    stock: 42,
    offer: false,
  },
  {
    id: 8,
    img: "https://picsum.photos/300?random=8",
    title: "Mango Juice",
    code: "FD1008",
    category: "Drinks",
    discountPercent: 7,
    price: 150,
    discountPrice: 139,
    stock: 70,
    offer: false,
  },
  {
    id: 9,
    img: "https://picsum.photos/300?random=9",
    title: "Cheese Pasta",
    code: "FD1009",
    category: "Pasta",
    discountPercent: 18,
    price: 450,
    discountPrice: 369,
    stock: 29,
    offer: true,
  },
  {
    id: 10,
    img: "https://picsum.photos/300?random=10",
    title: "Spicy Noodles",
    code: "FD1010",
    category: "Noodles",
    discountPercent: 9,
    price: 300,
    discountPrice: 273,
    stock: 48,
    offer: false,
  },
  {
    id: 11,
    img: "https://picsum.photos/300?random=11",
    title: "Chicken Burger",
    code: "FD1011",
    category: "Burger",
    discountPercent: 14,
    price: 290,
    discountPrice: 249,
    stock: 37,
    offer: true,
  },
  {
    id: 12,
    img: "https://picsum.photos/300?random=12",
    title: "Veg Pizza",
    code: "FD1012",
    category: "Pizza",
    discountPercent: 11,
    price: 600,
    discountPrice: 534,
    stock: 18,
    offer: true,
  },
  {
    id: 13,
    img: "https://picsum.photos/300?random=13",
    title: "Fried Chicken",
    code: "FD1013",
    category: "Chicken",
    discountPercent: 16,
    price: 550,
    discountPrice: 462,
    stock: 31,
    offer: true,
  },
  {
    id: 14,
    img: "https://picsum.photos/300?random=14",
    title: "Donut Box",
    code: "FD1014",
    category: "Dessert",
    discountPercent: 13,
    price: 350,
    discountPrice: 304,
    stock: 25,
    offer: false,
  },
  {
    id: 15,
    img: "https://picsum.photos/300?random=15",
    title: "Chicken Wrap",
    code: "FD1015",
    category: "Fast Food",
    discountPercent: 10,
    price: 260,
    discountPrice: 234,
    stock: 40,
    offer: false,
  },
  {
    id: 16,
    img: "https://picsum.photos/300?random=16",
    title: "Vanilla Ice Cream",
    code: "FD1016",
    category: "Dessert",
    discountPercent: 6,
    price: 200,
    discountPrice: 188,
    stock: 44,
    offer: false,
  },
  {
    id: 17,
    img: "https://picsum.photos/300?random=17",
    title: "BBQ Pizza",
    code: "FD1017",
    category: "Pizza",
    discountPercent: 17,
    price: 720,
    discountPrice: 598,
    stock: 19,
    offer: true,
  },
  {
    id: 18,
    img: "https://picsum.photos/300?random=18",
    title: "Orange Juice",
    code: "FD1018",
    category: "Drinks",
    discountPercent: 5,
    price: 140,
    discountPrice: 133,
    stock: 66,
    offer: false,
  },
  {
    id: 19,
    img: "https://picsum.photos/300?random=19",
    title: "Seafood Pasta",
    code: "FD1019",
    category: "Sea Food",
    discountPercent: 20,
    price: 850,
    discountPrice: 680,
    stock: 14,
    offer: true,
  },
  {
    id: 20,
    img: "https://picsum.photos/300?random=20",
    title: "Chicken Nuggets",
    code: "FD1020",
    category: "Snacks",
    discountPercent: 9,
    price: 240,
    discountPrice: 218,
    stock: 51,
    offer: false,
  },

  // 21 - 50

  {
    id: 21,
    img: "https://picsum.photos/300?random=21",
    title: "Beef Burger",
    code: "FD1021",
    category: "Burger",
    discountPercent: 15,
    price: 340,
    discountPrice: 289,
    stock: 36,
    offer: true,
  },
  {
    id: 22,
    img: "https://picsum.photos/300?random=22",
    title: "Chicken Sub",
    code: "FD1022",
    category: "Fast Food",
    discountPercent: 8,
    price: 280,
    discountPrice: 257,
    stock: 40,
    offer: false,
  },
  {
    id: 23,
    img: "https://picsum.photos/300?random=23",
    title: "Strawberry Shake",
    code: "FD1023",
    category: "Drinks",
    discountPercent: 10,
    price: 190,
    discountPrice: 171,
    stock: 58,
    offer: true,
  },
  {
    id: 24,
    img: "https://picsum.photos/300?random=24",
    title: "Cheese Fries",
    code: "FD1024",
    category: "Snacks",
    discountPercent: 7,
    price: 210,
    discountPrice: 195,
    stock: 49,
    offer: false,
  },
  {
    id: 25,
    img: "https://picsum.photos/300?random=25",
    title: "Pepperoni Pizza",
    code: "FD1025",
    category: "Pizza",
    discountPercent: 20,
    price: 780,
    discountPrice: 624,
    stock: 16,
    offer: true,
  },

  {
    id: 26,
    img: "https://picsum.photos/300?random=26",
    title: "Chocolate Muffin",
    code: "FD1026",
    category: "Bakery",
    discountPercent: 12,
    price: 160,
    discountPrice: 141,
    stock: 62,
    offer: true,
  },
  {
    id: 27,
    img: "https://picsum.photos/300?random=27",
    title: "Chicken Momos",
    code: "FD1027",
    category: "Snacks",
    discountPercent: 11,
    price: 260,
    discountPrice: 231,
    stock: 38,
    offer: false,
  },
  {
    id: 28,
    img: "https://picsum.photos/300?random=28",
    title: "Thai Soup",
    code: "FD1028",
    category: "Soup",
    discountPercent: 9,
    price: 300,
    discountPrice: 273,
    stock: 27,
    offer: false,
  },
  {
    id: 29,
    img: "https://picsum.photos/300?random=29",
    title: "Garlic Bread",
    code: "FD1029",
    category: "Bakery",
    discountPercent: 5,
    price: 180,
    discountPrice: 171,
    stock: 57,
    offer: false,
  },
  {
    id: 30,
    img: "https://picsum.photos/300?random=30",
    title: "Chicken Kebab",
    code: "FD1030",
    category: "Chicken",
    discountPercent: 14,
    price: 420,
    discountPrice: 361,
    stock: 22,
    offer: true,
  },

  {
    id: 31,
    img: "https://picsum.photos/300?random=31",
    title: "Tandoori Pizza",
    code: "FD1031",
    category: "Pizza",
    discountPercent: 18,
    price: 820,
    discountPrice: 672,
    stock: 13,
    offer: true,
  },
  {
    id: 32,
    img: "https://picsum.photos/300?random=32",
    title: "Lemon Juice",
    code: "FD1032",
    category: "Drinks",
    discountPercent: 6,
    price: 120,
    discountPrice: 113,
    stock: 74,
    offer: false,
  },
  {
    id: 33,
    img: "https://picsum.photos/300?random=33",
    title: "Fish Fry",
    code: "FD1033",
    category: "Sea Food",
    discountPercent: 13,
    price: 480,
    discountPrice: 417,
    stock: 26,
    offer: true,
  },
  {
    id: 34,
    img: "https://picsum.photos/300?random=34",
    title: "Chicken Roll",
    code: "FD1034",
    category: "Fast Food",
    discountPercent: 10,
    price: 230,
    discountPrice: 207,
    stock: 41,
    offer: false,
  },
  {
    id: 35,
    img: "https://picsum.photos/300?random=35",
    title: "Brownie Cake",
    code: "FD1035",
    category: "Dessert",
    discountPercent: 15,
    price: 380,
    discountPrice: 323,
    stock: 24,
    offer: true,
  },

  {
    id: 36,
    img: "https://picsum.photos/300?random=36",
    title: "Chicken Pasta",
    code: "FD1036",
    category: "Pasta",
    discountPercent: 9,
    price: 460,
    discountPrice: 418,
    stock: 32,
    offer: false,
  },
  {
    id: 37,
    img: "https://picsum.photos/300?random=37",
    title: "Veg Sandwich",
    code: "FD1037",
    category: "Snacks",
    discountPercent: 8,
    price: 210,
    discountPrice: 193,
    stock: 50,
    offer: false,
  },
  {
    id: 38,
    img: "https://picsum.photos/300?random=38",
    title: "Cappuccino",
    code: "FD1038",
    category: "Drinks",
    discountPercent: 7,
    price: 240,
    discountPrice: 223,
    stock: 45,
    offer: false,
  },
  {
    id: 39,
    img: "https://picsum.photos/300?random=39",
    title: "BBQ Wings",
    code: "FD1039",
    category: "Chicken",
    discountPercent: 16,
    price: 520,
    discountPrice: 437,
    stock: 21,
    offer: true,
  },
  {
    id: 40,
    img: "https://picsum.photos/300?random=40",
    title: "Shrimp Burger",
    code: "FD1040",
    category: "Sea Food",
    discountPercent: 14,
    price: 390,
    discountPrice: 335,
    stock: 18,
    offer: true,
  },

  {
    id: 41,
    img: "https://picsum.photos/300?random=41",
    title: "Chicken Hotdog",
    code: "FD1041",
    category: "Fast Food",
    discountPercent: 10,
    price: 250,
    discountPrice: 225,
    stock: 47,
    offer: false,
  },
  {
    id: 42,
    img: "https://picsum.photos/300?random=42",
    title: "Chocolate Shake",
    code: "FD1042",
    category: "Drinks",
    discountPercent: 11,
    price: 220,
    discountPrice: 196,
    stock: 55,
    offer: true,
  },
  {
    id: 43,
    img: "https://picsum.photos/300?random=43",
    title: "Cheese Burger",
    code: "FD1043",
    category: "Burger",
    discountPercent: 12,
    price: 310,
    discountPrice: 272,
    stock: 39,
    offer: true,
  },
  {
    id: 44,
    img: "https://picsum.photos/300?random=44",
    title: "Veg Pasta",
    code: "FD1044",
    category: "Pasta",
    discountPercent: 8,
    price: 420,
    discountPrice: 386,
    stock: 30,
    offer: false,
  },
  {
    id: 45,
    img: "https://picsum.photos/300?random=45",
    title: "Chicken Supreme Pizza",
    code: "FD1045",
    category: "Pizza",
    discountPercent: 20,
    price: 890,
    discountPrice: 712,
    stock: 11,
    offer: true,
  },

  {
    id: 46,
    img: "https://picsum.photos/300?random=46",
    title: "Ice Latte",
    code: "FD1046",
    category: "Drinks",
    discountPercent: 6,
    price: 260,
    discountPrice: 244,
    stock: 53,
    offer: false,
  },
  {
    id: 47,
    img: "https://picsum.photos/300?random=47",
    title: "Chicken Popcorn",
    code: "FD1047",
    category: "Snacks",
    discountPercent: 13,
    price: 280,
    discountPrice: 243,
    stock: 34,
    offer: true,
  },
  {
    id: 48,
    img: "https://picsum.photos/300?random=48",
    title: "Red Velvet Cake",
    code: "FD1048",
    category: "Dessert",
    discountPercent: 18,
    price: 620,
    discountPrice: 508,
    stock: 17,
    offer: true,
  },
  {
    id: 49,
    img: "https://picsum.photos/300?random=49",
    title: "Chicken Chowmein",
    code: "FD1049",
    category: "Noodles",
    discountPercent: 9,
    price: 340,
    discountPrice: 309,
    stock: 28,
    offer: false,
  },
  {
    id: 50,
    img: "https://picsum.photos/300?random=50",
    title: "Seafood Platter",
    code: "FD1050",
    category: "Sea Food",
    discountPercent: 22,
    price: 1200,
    discountPrice: 936,
    stock: 9,
    offer: true,
  },
];

export default foodProducts;